### ISSUE TITLE
[BUG] DeletePA missing error handling when it is used to delete a public address that does not exists

### ISSUE THREAD

**Issue by travisim** [AY2425S1-CS2103T-T08-1/tp#156]
Input: Deletepa 1 pa/BTC l/default
Output: No change to addressbook.json
<img width="905" alt="Screenshot 2024-11-06 at 8 50 28 PM" src="https://github.com/user-attachments/assets/dc907959-cce1-4f9b-be18-7e5df3395010">

**Comment by chongtzezhao** [comment]
fixed in #145
