### ISSUE TITLE
[Bug] deletepa is not deleting public address

### ISSUE THREAD

**Issue by Airiinnn** [AY2425S1-CS2103T-T08-1/tp#159]
Any command in the valid format always returns something like:

`Deleted Person's Public Address: PublicAddressesComposition{{BTC=[DeFaUlT: 2345, idk what: 3456, default but long: 4567, default: 6789, default: 1234]}}`

For labels that do not exist, also returns this.

For labels that do exist, it does not get deleted.

**Comment by TheRareFox** [comment]
Addressed in PR #171
