### ISSUE TITLE
[BUG] AddPA should prevent the addition of 1 pa if label of that pa already exists

### ISSUE THREAD

**Issue by travisim** [AY2425S1-CS2103T-T08-1/tp#167]
further elaboration: for 1 person, label names can be duplicated across networks but within 1 network, all label names should be unique
output: 
![Uploading Screenshot 2024-11-07 at 9.25.35 PM.png…]()

**Comment by chongtzezhao** [comment]
This behaviour is no longer present on the current version and can be closed. tagging @travisim for confirmation.

**Comment by chongtzezhao** [comment]
fixed in #161
