### ISSUE TITLE
[BUG] DeletePA does not display error message/displays wrong message when trying to delete a PA with label that does not exists

### ISSUE THREAD

**Issue by travisim** [AY2425S1-CS2103T-T08-1/tp#176]
input: deletepa 1 pa/BTC l/default3
output:
<img width="738" alt="Screenshot 2024-11-07 at 10 04 28 PM" src="https://github.com/user-attachments/assets/3451536a-b993-420d-ab29-a49e9916ad85">

**Comment by chongtzezhao** [comment]
Fixed in #145
