### ISSUE TITLE
[PE-D][Tester C] Inconsistency in input acceptance across different fields

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-1/tp#216]
Currently name only accept alphnumeric input, accepting special characters like '-' and other scripts like Chinese characters would allow users more freedom and cater to a greater user group. 

It is justifiable to only accept alphnumeric characters if the argument is about simplicity or to be consistent with other fields, but oddly enough address accepts any value.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Wxy2003-xy/ped#7

**Comment by travisim** [comment]
NOT_IN_SCOPE
