### ISSUE TITLE
[PE-D][Tester E] retrievepa only returns one public address if a person has multiple public addresses with the same label

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-1/tp#228]
After “retrievepa l/daily” was entered:

![Screenshot 2024-11-08 142732.png](https://raw.githubusercontent.com/foothaddeus/ped/main/files/9e1e37f4-b828-41b2-a33b-152196ee2d1d.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: foothaddeus/ped#6

**Comment by Airiinnn** [comment]
Valid. 

Duplicate of #247

**Comment by Airiinnn** [comment]
Will be non-issue after public address uniquness is enforced.
