### ISSUE TITLE
[PE-D][Tester D] editpa functionality does not work at all. 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-1/tp#232]
![image.png](https://raw.githubusercontent.com/emmannyyy/ped/main/files/48646b0b-b74d-4d60-9101-b307c5de1aa9.png)

Command given:
 editpa 2 c/eth l/wallet1 pa/14qViLJfdGaP4EeHnDyJbEGQysnCpwk3gd

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: emmannyyy/ped#13

**Comment by Airiinnn** [comment]
Invalid.

Mistake on users' part. User's label is `wallet1 e.g.,` as in the screenshot.

**Comment by travisim** [comment]
bad issue
