### ISSUE TITLE
[PE-D][Tester D] Names do not allow for "s/o" even if it may be a legitimate name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-1/tp#249]
![image.png](https://raw.githubusercontent.com/emmannyyy/ped/main/files/12e44dc0-1bd6-4812-83ee-6e7dd5851f4c.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: emmannyyy/ped#17

**Comment by travisim** [comment]
![Image](https://github.com/user-attachments/assets/e4d1cb2b-c16b-4d92-902f-69f68dcaf1f1)
